---
version: '3.4'
services:
  shell:
    image: ubuntu
    volumes:
      - cache:/home/app/.cache
      - ./data:/home/app/data
    user: root
    entrypoint: sh -c "tail -f /dev/null"
  frontend:
    restart: no
    image: tiberiuichim/llm-chat-frontend:0.1
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://test-gpu.pdmz.eea:8060
    command: sh -c 'cd /app; find .next | grep ".js" | xargs sed -i "s#http://localhost:8080#http://test-gpu-pdmz.eea:8060#g"; node server.js'
    #entrypoint: /app/entrypoint.sh
    #volumes:
      #- ./frontend/entrypoint.sh:/app/entrypoint.sh
    # command: /home/app/.local/bin/uvicorn main:app --port=8060
    # env_file:
    #   - ./.env.example
    #   - ./.env

  chat:
    restart: no
    image: tiberiuichim/llm-chat-backend:0.1
    build: .
    ports:
      - 8060:8060
    environment:
      CONTAINER_PORT: 8060
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    command: /home/app/.local/bin/uvicorn main:app --host 0.0.0.0 --port=8060
    # entrypoint: sh -c "tail -f /dev/null"
    env_file:
      - ./.env.example
      - ./.env
    volumes:
      - ./data:/home/app/chat/data
      - cache:/home/app/.cache
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

  weaviate:
    restart: no
    # restart: on-failure:0
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8090'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.22.6
    ports:
    - 8090:8090
    - 50051:50051
    volumes:
    - ./data/weaviate:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'

volumes:
  cache: {}
